# Task Manager routes (by path)
server {
  listen 80;
  server_name vera-linno-task-management.proxy.itcollege.ee localhost 127.0.0.1;

  location = / {
    return 302 /ts/;
  }

  location /ts/ {
    proxy_pass http://task-manager-ts/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header Connection "";
  }

  location /js/ {
    proxy_pass http://task-manager-js/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header Connection "";
  }
}

# Assignment 4 routing 
server {
  listen 80;
  server_name vera-linno-a4.proxy.itcollege.ee;

  location / {
    proxy_pass http://127.0.0.1:86;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header Connection "";
  }
}

# Assignment 5 routing
server {
  listen 80;
  server_name vera-linno-a5.proxy.itcollege.ee;

  location / {
    proxy_pass http://127.0.0.1:87;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header Connection "";
  }
}
